### PR TITLE
Php 5.5.9 ubuntu 14.04 (based on #39)

### PR DESCRIPTION
**Pull request by fpapadopou**
### ChangeLog
- Replaces #17 and #19 originally authored by @tzikis and reviewed by @spiliot (fixes all issues that came up during the review process)
- Adds proper Travis CI configuration for PHP 5.3, 5.4, 5.5
- Revamps the (functional) tests. Adds test cases for external cores/variants. 
- Adds code that removes all weird paths from linker errors and a related functional test.
- Includes #34 which revises the parameters.yml file.
- Adds code that removes the **`userId_cb_personal_lib`** from the compiler error output
- Updates Symfony & PHPUnit
- Makes installation scripts compatible to PHP 5.5.9 and Ubuntu 14.04

### CODE REVIEW

**Comment by fpapadopou** [comment]
Reviewed up to dbaa56d

**Comment by fpapadopou** [comment]
@spiliot please review commits ccdf2da through add4d26

**Comment by fpapadopou** [comment]
Had to revert dbaa56d6ff6e7c6eb1ebd308c51700aa47e70ae1, 1dbc0d021f59377bcee52e5ca2d5b997fa3f2195 and 2fa95951a3fef79c282355252a3fc7b7924b5531 since we are not to introduce safe HTML handling yet.

**Comment by dastergon** [comment]
@spiliot the PR is still ready for review, how do we proceed ?

**Pull request merged**
